---
title: "2019 Playoffs?!? League Champion's Address"
author: "Jerry's Belt Buckle\n(Chris Umphlett)"
date: "(updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)

library(tidyverse)
```

``` {r create_loop_parms, echo = FALSE}

teams <- c("Jerry's Belt Buckle",
           "The Institute",
           "Kayak Pirates",
           "The Maccabee",
           "The Commish",
           "K Rabbits",
           "Black is for Sunday",
           "The Icon",
           "40 Acres and a Mule",
           "Show Me Da Money!"
           )

record <- c("12 - 2 (1st)",
            "12 - 2 (2nd)",
            "10 - 4 (3rd)",
            "7 - 7 (4th)",
            "5 - 9 (5th)",
            "5 - 9 (6th)",
            "6 - 8 (7th)",
            "6 - 8 (8th)",
            "4 - 10 (9th)",
            "3 - 11 (10th)"
            )

finish <- c("Champion",
            "First Loser",
            "3rd",
            "4th",
            "5th",
            "6th",
            "7th",
            "8th",
            "Did not qualify",
            "Did not qualify"
            )

```

``` {r loop_function, results = "asis"}
i <- 1

xarin_fun <- function() {

  for (team in teams) {

    cat("---")
    cat(paste0("\n # ", team, "\n\n"))
    cat(paste0("Regular season record: ", record[i], "\n\n"))
    cat(paste0("Playoff finish: ", finish[i], "\n\n"))
    i <- i + 1
  }
}

xarin_fun()
```
